# Generated by Django 3.1 on 2020-09-21 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('ilosc_czlonkow', models.IntegerField()),
                ('manager', models.CharField(choices=[('T', 'Tak'), ('N', 'Nie')], default='T', max_length=1)),
                ('min_kwota_zlecenia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fundusz', models.SmallIntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'zespoły',
            },
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Nazwa samochodu, np. Opel Astra', max_length=50)),
                ('paliwo', models.CharField(choices=[('B', 'benzyna'), ('D', 'diesel'), ('G', 'gaz')], default='B', max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zespol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samochody', to='muzyk.zespol')),
            ],
            options={
                'verbose_name_plural': 'samochody',
            },
        ),
    ]
