# Generated by Django 3.1 on 2020-09-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_czlonkow', models.SmallIntegerField()),
                ('min_kwota_zlecenia', models.SmallIntegerField()),
                ('samochod', models.CharField(max_length=200)),
                ('spalanie_samochodu', models.FloatField()),
                ('fundusz', models.SmallIntegerField()),
            ],
        ),
    ]
