# Generated by Django 3.1 on 2020-09-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyk', '0002_samochod_ile_pali'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samochod',
            old_name='ile_pali',
            new_name='ile_litrow_pali_na_100_km',
        ),
        migrations.AddField(
            model_name='zespol',
            name='sklad_zespolu',
            field=models.TextField(blank=True, help_text='Można wypisać tu członków zespołu'),
        ),
        migrations.AlterField(
            model_name='zespol',
            name='ilosc_czlonkow',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zespol',
            name='min_kwota_zlecenia',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
